# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reward < Formula
  desc "Reward is CLI utility for orchestrating Docker based development environments."
  homepage ""
  version "0.7.2"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "mutagen" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_x86_64.tar.gz"
      sha256 "cfb0ee8d19e2fc13e2ca54215e9e1519d3e8218febede1a330c4434847d0e812"

      def install
        bin.install "reward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_arm64.tar.gz"
      sha256 "e28846b4f837f66443eadacd422955a723340de42a8e0198242373b96f13a5ce"

      def install
        bin.install "reward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_x86_64.tar.gz"
        sha256 "a2aee737bf504c3bee25041115b73e72bb7563223b366f7a1ca94413646e8a73"

        def install
          bin.install "reward"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_aarch64.tar.gz"
        sha256 "725ab8660bedff7eff21c3323f72dcc1edb1c95d3a4612a49fa2a0bf5602a526"

        def install
          bin.install "reward"
        end
      end
    end
  end
end
