# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reward < Formula
  desc "Reward is CLI utility for orchestrating Docker based development environments."
  homepage ""
  version "0.7.2"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "mutagen" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_x86_64.tar.gz"
      sha256 "72ae051e1937017fb336f7c2805b7c492fb6d9d3b6b2af36ad0cc41439fda00b"

      def install
        bin.install "reward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_arm64.tar.gz"
      sha256 "95f417bdb9f961bbbaec682d0f126f94a5dcdeca95c67bec3671e0353de56c1e"

      def install
        bin.install "reward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_x86_64.tar.gz"
        sha256 "9f21b881411ba3eaea06989b212ebcac59aa9ea032b79acb4fe9778c118c22c1"

        def install
          bin.install "reward"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_aarch64.tar.gz"
        sha256 "f821cc396094abe29420b5e597d5fadeaeacbe1692db3788680635a24340c05b"

        def install
          bin.install "reward"
        end
      end
    end
  end
end
