# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reward < Formula
  desc "Reward is CLI utility for orchestrating Docker based development environments."
  homepage ""
  version "0.7.2"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "mutagen" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_x86_64.tar.gz"
      sha256 "0f40ed09f5fdef42c2a4489df83feab3c193c0d4ffd6898821619bb2ba305f52"

      def install
        bin.install "reward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Darwin_arm64.tar.gz"
      sha256 "3aa38bc12e1a16d03f08a68e6dcbd7ab95e6dbd952556acebb7c6baa58ae21ef"

      def install
        bin.install "reward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_x86_64.tar.gz"
        sha256 "fa2a41b297f9f3615d84fe27b95774154aa294777d136f9512cb3314ceee3718"

        def install
          bin.install "reward"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.2/reward_Linux_aarch64.tar.gz"
        sha256 "f2a68b179b1acd5e127e6b7e1647c33ca37b12acee6d961cbdd240355a472284"

        def install
          bin.install "reward"
        end
      end
    end
  end
end
