# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reward < Formula
  desc "Reward is CLI utility for orchestrating Docker based development environments."
  homepage ""
  version "0.7.0"
  license "MIT"

  depends_on "docker" => :optional
  depends_on "mutagen" => :optional

  on_macos do
    on_intel do
      url "https://github.com/rewardenv/reward/releases/download/v0.7.0/reward_Darwin_x86_64.tar.gz"
      sha256 "ba2a50e7126602d4ac9ee8b2cb3dfa639995e770bf5cfaeabbd57b75fbb59f40"

      def install
        bin.install "reward"
      end
    end
    on_arm do
      url "https://github.com/rewardenv/reward/releases/download/v0.7.0/reward_Darwin_arm64.tar.gz"
      sha256 "6bf48da629bd66177d1e888629541434ffa0548fe23043cec942fadb56a1d996"

      def install
        bin.install "reward"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.0/reward_Linux_x86_64.tar.gz"
        sha256 "498a039e21e33fda813618ca6bdc96a4d109128b4ce93891d3ab20c7f0779462"

        def install
          bin.install "reward"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rewardenv/reward/releases/download/v0.7.0/reward_Linux_aarch64.tar.gz"
        sha256 "f6ce487a260ba8bc717b76ff147b0df0c4447caf1842bea56893c91c5b07208c"

        def install
          bin.install "reward"
        end
      end
    end
  end
end
