# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reward < Formula
  desc "Reward is CLI utility for orchestrating Docker based development environments."
  homepage ""
  version "0.1.18-beta"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rewardenv/reward/releases/download/v0.1.18-beta/reward_Darwin_x86_64.tar.gz"
    sha256 "404d5a58e15e42fd211121fc6b08bc9e34096d2e20a1cb0e913697b7032337a5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rewardenv/reward/releases/download/v0.1.18-beta/reward_Linux_x86_64.tar.gz"
    sha256 "bf1789b194c88023de49fa8c5707bf2aaaf21f1e9a8d93d793336922156ccecf"
  end

  depends_on "docker" => :optional
  depends_on "docker-edge" => :optional
  depends_on "mutagen" => :optional

  def install
    bin.install "reward"
  end
end
