# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RewardGreeter < Formula
  desc "Reward-Greeter is a sample plugin for Reward."
  homepage ""
  version "0.1.0"
  license "MIT"

  depends_on "reward" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rewardenv/reward-plugin-template/releases/download/v0.1.0/reward-greeter_Darwin_x86_64.tar.gz"
      sha256 "bca147955113fdbb3a30f952a468dd33e1f24ec1bab330467dfbabcf568942a3"

      def install
        bin.install "reward-greeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rewardenv/reward-plugin-template/releases/download/v0.1.0/reward-greeter_Darwin_arm64.tar.gz"
      sha256 "4c2489238bedc30d42c6fce2eeb0dc4078678a3963af6a9c7fa9bd5ef657009e"

      def install
        bin.install "reward-greeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rewardenv/reward-plugin-template/releases/download/v0.1.0/reward-greeter_Linux_x86_64.tar.gz"
      sha256 "ec8f76439472be154099d6552cf9e76fca5cb7ffc15a3a68fd7d618ccf50f738"

      def install
        bin.install "reward-greeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rewardenv/reward-plugin-template/releases/download/v0.1.0/reward-greeter_Linux_aarch64.tar.gz"
      sha256 "d4e72d82d9b20aa9da0895d114c069d8c994be737bc747667dc00207eeadf1d9"

      def install
        bin.install "reward-greeter"
      end
    end
  end
end
